language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g gulp
  - npm install -g bower
  - npm install -g karma-cli
  - bower install
env:
  global:
    - secure: PmrQ8HmfT4ieY1C5hwBaZaag+kv+zLWCcmk+bYAEi7NgUY5k9b/KNBDVtj+67DpmG9mLhS7orHE7Vsd4msBcrfFTSZR5lh17yNSCIUU2RvbAvA8YoDw1Mzrd+Xp9UQNBxYCyyKDXH8nHP/XIy2KNSlJKTaIImmUSVHPHjfLGFsc=
    - secure: WSE7YC9SAWtu7FFNZNGF2Ybarm4lLLq7Dhu4hGgZsgRWOwC7SMC71PSeZp6eEcPQ2tVelBf+QYwWi6oWdAJLS/SwG4XVr1/bjILyyoz66quqNnlGdgaMvcMFz7R15QiVTjMdxQRGEmmz8ov4a4a2RtR4Xnhw2VJawtggOgeEus8=
addons:
  sauce_connect: true