language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g gulp
  - npm install -g bower
  - npm install -g karma-cli
  - bower install
env:
  global:
    - secure: MalyfshCdi+yvZSlNEegxVbcRbiFqzXJfmngAD2ExHd6BmnqcEc/OI9lJqYEviKwon4OBWfYCOPXsere0YBJG7hdJPwMRjUflJFgN8pibsopCRoPfAIM4KwWJK57U3Wv7XSkOb/3TRrR0XGv7XTCh42e78XkJJU/dfcu/d5b2wY=
    - secure: fZLxstss4BJE1mOKMadADoRyumqUprYdaVfRuCfrkNY9f1VAyiwdfB6uWOl5X9atyaOeEG+LYZhKoDS6Yj3rTTjmzF7dO/ledkdNq6Rx83bRfSVjVi4bghVbDR/gvq6jrnhQ3bAP9Py7KuJ50BjQG1f1D4FVoNYWebA4/ZDCL1o=
addons:
  sauce_connect: true